export const courses = [
  {
    title: "The Complete Web Development Bootcamp",
    description: [
      "HTML, CSS & Bootstrap",
      "JavaScript ES6, DOM  & jQuery",
      "Git and GitHub",
      "Introduction to Node, Express & EJS",
      "Database intro to SQL & NoSQL",
      "Building RESTful APIs",
      "Authentication & Security",
    ],
    progress: 100,
    author: "Dr. Angela Yu",
    img: "https://img-c.udemycdn.com/course/240x135/1565838_e54e_16.jpg",
  },
  {
    title: "CSS- The Complete Guide",
    subtitle: "(incl. Flexbox, Grid & Sass)",
    description: [
      "CSS selectors and specificity",
      "Positioning  & Box model",
      " Flexbox & Grid layouts",
      "Responsive design & media queries",
      "Transitions & Animations",
      "Sass (Nesting & Mixins)",
    ],
    progress: 100,
    author: "Academind by Maximilian Schwarzmüller",
    img: "https://img-c.udemycdn.com/course/240x135/1561458_7f3b_2.jpg",
  },
  {
    title: "React- The Complete Guide",
    subtitle: "(incl. Hooks,Router,Redux)",
    description: [
      "JSX syntax",
      "Lifecycle methods and hooks",
      "Working with APIs",
      "Building custom React Hooks",
      "Form handling and validation",
      "React Router for routing and navigation",
      "State management with Redux",
    ],
    progress: 100,
    author: "Academind by Maximilian Schwarzmüller",
    img: "https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg",
  },
  {
    title: "The MERN Fullstack Guide",
    subtitle: "(React, NodeJS, Express & MongoDB)",
    description: [
      "Setting up and configuring MongoDB ",
      "Building apps with Node.js and Express.js",
      "User Authentication & Authorization",
      "Connecting  React to Server & Server to Database",
      "Deploying MERN apps",
    ],
    progress: 100,
    author: "Academind by Maximilian Schwarzmüller",
    img: "https://img-c.udemycdn.com/course/240x135/2640372_5b44_5.jpg",
  },
  {
    title: "Understanding TypeScript",
    subtitle: "2023 Edition",
    description: [
      "TypeScript basics & basic types",
      "TypeScript Compiler & Configuration",
      "Classes & Interfaces",
      "Advanced Types, Generics & Decorators",
      "React & Node with TypeScript",
    ],
    progress: 100,
    author: "Academind by Maximilian Schwarzmüller",
    img: "https://img-c.udemycdn.com/course/240x135/947098_02ec_2.jpg",
  },
  {
    title: "React Native",
    subtitle: "The Practical Guide",
    description: [
      "Components, Layouts & Styling",
      "Adapting UI to Platform & Device Size",
      "React Native Navigation",
      "Using Native Device features",
      "Push notifications",
      "Publishing React Native apps",
    ],
    progress: 100,
    author: "Academind by Maximilian Schwarzmüller",
    img: "https://img-c.udemycdn.com/course/240x135/1436092_2024_4.jpg",
  },
];
